require 'bundler/setup'
require './spec/support/silence_warnings.rb'
require 'logger'
require 'combustion'

Combustion::Database.instance_eval do
  def setup(options)
    ActiveRecord::Base.configurations = YAML.safe_load(ERB.new(File.read("#{Rails.root}/config/database.yml")).result, aliases: true)
  end
end

Combustion.initialize! :active_record, :action_controller do
  config.load_defaults "#{Rails::VERSION::MAJOR}.#{Rails::VERSION::MINOR}"
  config.active_support.deprecation = -> (message, _callstack, _deprecator) do
    warn message
  end
  config.cache_classes = false
  config.log_level = :debug
  config.secret_key_base = 'dummy'
  config.active_record.schema_format = ENV.fetch('SCHEMA_FORMAT', 'sql').to_sym
  if Gem::Requirement.new('~> 6.1').satisfied_by?(Gem::Version.new(Rails.version))
    config.active_record.legacy_connection_handling = false
  end
  if ENV['SKIP_MODEL_EAGER_LOAD']
    config.eager_load_paths -= Rails.application.config.paths['app/models'].to_a
    Rails.autoloaders.main.ignore Rails.application.config.paths['app/models'].to_a
  end
end

load 'active_record/railties/databases.rake'
Combustion::Application.load_tasks
