require 'bundler/setup'
require './spec/support/silence_warnings.rb'
require 'combustion'

Combustion::Database.instance_eval do
  def setup(options)
    ActiveRecord::Base.configurations = YAML.load(ERB.new(File.read("#{Rails.root}/config/database.yml")).result)
  end
end

Combustion.initialize! :active_record, :action_controller do
  config.cache_classes = false
  config.log_level = :debug
  config.active_record.schema_format = ENV.fetch('SCHEMA_FORMAT', 'sql').to_sym
  if ENV['SKIP_MODEL_EAGER_LOAD']
    config.eager_load_paths -= Rails.application.config.paths['app/models'].to_a
  end
end

load 'active_record/railties/databases.rake'
Combustion::Application.load_tasks
